apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colorpalette-ingress
  namespace: colorpalette
  labels:
    app: colorpalette
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: colorpalette.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colorpalette-service
                port:
                  number: 80
